import { TimelineEvent } from "../Entities/TimelineEvent";
import {SeedEventsData, SeedsEnum} from "./SeedEventsDataType";

export const UkEvents: SeedEventsData = {
    Name: "UK history",
    Value: SeedsEnum.UkEvents,
    Events: [
        new TimelineEvent("1", [-800000], "First humans arrive in Britain", "Archaeological evidence suggests that the earliest humans arrived in what is now Britain around 800,000 years ago, during the Paleolithic era."),
        new TimelineEvent("2", [-4000], "Neolithic farmers settle in Britain", "Around 4000 BCE, people began to settle, farm, and build monuments such as Stonehenge, marking the start of the Neolithic period in Britain."),
        new TimelineEvent("3", [-2500], "Construction of Stonehenge begins", "Stonehenge, one of the most famous prehistoric monuments in the world, was constructed in several stages starting around 2500 BCE."),
        new TimelineEvent("4", [-800], "Iron Age and Celtic culture in Britain", "The Iron Age saw the arrival of the Celts, who brought new technologies and established tribal kingdoms across Britain."),
        new TimelineEvent("5", [43], "Roman conquest of Britain", "The Romans, led by Emperor Claudius, invaded and began the conquest of Britain in 43 CE, establishing the province of Britannia."),
        new TimelineEvent("6", [122], "Construction of Hadrian's Wall", "Hadrian's Wall was built by the Romans to protect the northern border of their province from tribes in what is now Scotland."),
        new TimelineEvent("7", [410], "End of Roman rule in Britain", "Roman administration and legions withdrew from Britain, leaving the local population to govern themselves."),
        new TimelineEvent("8", [450], "Anglo-Saxon settlement begins", "After the Romans left, groups such as the Angles, Saxons, and Jutes migrated to Britain, forming several kingdoms."),
        new TimelineEvent("9", [597], "Arrival of St Augustine", "St Augustine arrived in Kent to convert the Anglo-Saxons to Christianity, becoming the first Archbishop of Canterbury."),
        new TimelineEvent("10", [793], "Viking raid on Lindisfarne", "The first major Viking raid in Britain occurred at the monastery of Lindisfarne, marking the start of the Viking Age."),
        new TimelineEvent("11", [871], "Alfred the Great becomes King of Wessex", "Alfred the Great defended his kingdom against Viking invasions and promoted learning and legal reform."),
        new TimelineEvent("12", [927], "Athelstan becomes first King of England", "Athelstan united the various Anglo-Saxon kingdoms, becoming the first King of a unified England."),
        new TimelineEvent("13", [1066], "Battle of Hastings and Norman Conquest", "William the Conqueror defeated King Harold II at the Battle of Hastings, beginning Norman rule in England."),
        new TimelineEvent("14", [1086], "Domesday Book completed", "The Domesday Book was a great survey commissioned by William the Conqueror to assess land and resources in England."),
        new TimelineEvent("15", [1170], "Murder of Thomas Becket", "Archbishop Thomas Becket was murdered in Canterbury Cathedral, becoming a martyr and symbol of church-state conflict."),
        new TimelineEvent("16", [1215], "Magna Carta signed", "King John agreed to the Magna Carta, a charter limiting royal power and establishing certain legal rights."),
        new TimelineEvent("17", [1284], "Statute of Rhuddlan", "The Statute of Rhuddlan annexed Wales to the English crown, establishing English rule over Wales."),
        new TimelineEvent("18", [1314], "Battle of Bannockburn", "Scottish forces led by Robert the Bruce defeated the English, securing Scottish independence for a time."),
        new TimelineEvent("19", [1348], "Black Death arrives in Britain", "The Black Death, a devastating plague, killed a large proportion of the British population in the mid-14th century."),
        new TimelineEvent("20", [1381], "Peasants' Revolt", "A major uprising of peasants and workers in England, protesting taxes and social inequality."),
        new TimelineEvent("21", [1415], "Battle of Agincourt", "King Henry V led the English to a famous victory against the French during the Hundred Years' War."),
        new TimelineEvent("22", [1485], "Battle of Bosworth Field", "The last major battle of the Wars of the Roses, resulting in the death of Richard III and the start of the Tudor dynasty."),
        new TimelineEvent("23", [1534], "Act of Supremacy", "King Henry VIII declared himself Supreme Head of the Church of England, breaking from the Roman Catholic Church."),
        new TimelineEvent("24", [1588], "Defeat of the Spanish Armada", "The English navy defeated the Spanish Armada, establishing England as a major naval power."),
        new TimelineEvent("25", [1603], "Union of the Crowns", "James VI of Scotland became James I of England, uniting the crowns of England and Scotland."),
        new TimelineEvent("26", [1605], "Gunpowder Plot", "A failed attempt by Guy Fawkes and others to blow up the Houses of Parliament and assassinate King James I."),
        new TimelineEvent("27", [1642], "English Civil War begins", "Conflict broke out between supporters of King Charles I and Parliament, leading to a series of civil wars."),
        new TimelineEvent("28", [1649], "Execution of Charles I", "King Charles I was executed after being tried for treason, and England briefly became a republic."),
        new TimelineEvent("29", [1660], "Restoration of the monarchy", "The monarchy was restored under Charles II after the collapse of the republican government."),
        new TimelineEvent("30", [1665], "Great Plague of London", "The last major outbreak of bubonic plague in England, killing thousands in London."),
        new TimelineEvent("31", [1666], "Great Fire of London", "A devastating fire destroyed much of the City of London, leading to major rebuilding efforts."),
        new TimelineEvent("32", [1688], "Glorious Revolution", "William of Orange and Mary II took the throne, establishing constitutional monarchy and parliamentary supremacy."),
        new TimelineEvent("33", [1707], "Act of Union between England and Scotland", "The Act of Union created the Kingdom of Great Britain, uniting England and Scotland under one parliament."),
        new TimelineEvent("34", [1756], "Start of the Seven Years' War", "A global conflict involving Britain, which expanded its empire and influence overseas."),
        new TimelineEvent("35", [1776], "American Declaration of Independence", "The American colonies declared independence from Britain, leading to the American Revolutionary War."),
        new TimelineEvent("36", [1801], "Act of Union with Ireland", "The Act of Union joined Great Britain and Ireland, creating the United Kingdom of Great Britain and Ireland."),
        new TimelineEvent("37", [1805], "Battle of Trafalgar", "Admiral Lord Nelson led the British navy to victory over the French and Spanish fleets, securing British naval dominance."),
        new TimelineEvent("38", [1815], "Battle of Waterloo", "The Duke of Wellington defeated Napoleon at Waterloo, ending the Napoleonic Wars."),
        new TimelineEvent("39", [1832], "Great Reform Act", "The Great Reform Act reformed the British electoral system, expanding the right to vote and redistributing parliamentary seats."),
        new TimelineEvent("40", [1833], "Abolition of slavery in the British Empire", "The Slavery Abolition Act 1833 ended slavery throughout most of the British Empire."),
        new TimelineEvent("41", [1837], "Queen Victoria ascends the throne", "Queen Victoria began her long reign, marking the start of the Victorian era."),
        new TimelineEvent("42", [1851], "The Great Exhibition", "The Great Exhibition in London showcased British industry and innovation to the world."),
        new TimelineEvent("43", [1914], "Start of World War I", "Britain entered World War I, a global conflict that had a profound impact on British society and the world."),
        new TimelineEvent("44", [1918], "Representation of the People Act", "The Representation of the People Act 1918 gave the vote to all men over 21 and women over 30 in Britain."),
        new TimelineEvent("45", [1928], "Equal franchise for women", "The Representation of the People Act 1928 gave women the same voting rights as men in Britain."),
        new TimelineEvent("46", [1939], "Start of World War II", "Britain declared war on Germany, beginning its involvement in World War II."),
        new TimelineEvent("47", [1940], "Battle of Britain", "The Royal Air Force defended the UK against large-scale attacks by Nazi Germany's air force."),
        new TimelineEvent("48", [1942], "Beveridge Report published", "The Beveridge Report laid the foundations for the modern welfare state in Britain."),
        new TimelineEvent("49", [1945], "End of World War II in Europe", "Victory in Europe Day (VE Day) marked the end of World War II in Europe."),
        new TimelineEvent("50", [1948], "Establishment of the NHS", "The National Health Service (NHS) was founded, providing free healthcare to all UK residents."),
        new TimelineEvent("51", [1952], "Queen Elizabeth II becomes monarch", "Queen Elizabeth II ascended the throne following the death of her father, King George VI."),
        new TimelineEvent("52", [1956], "Suez Crisis", "A diplomatic and military crisis involving Britain, France, Egypt, and Israel over control of the Suez Canal."),
        new TimelineEvent("53", [1969], "First man on the moon", "Neil Armstrong became the first person to walk on the moon, watched by millions in the UK and worldwide."),
        new TimelineEvent("54", [1973], "UK joins the European Economic Community", "Britain joined the EEC, a precursor to the European Union, marking a major shift in economic policy."),
        new TimelineEvent("55", [1979], "Margaret Thatcher becomes Prime Minister", "Margaret Thatcher became the UK's first female Prime Minister, leading major economic and social reforms."),
        new TimelineEvent("56", [1982], "Falklands War", "Britain fought and won a conflict with Argentina over the Falkland Islands in the South Atlantic."),
        new TimelineEvent("57", [1997], "Devolution in Scotland and Wales", "Referendums led to the creation of the Scottish Parliament and Welsh Assembly, devolving powers from Westminster."),
        new TimelineEvent("58", [1998], "Good Friday Agreement", "The Good Friday Agreement brought peace to Northern Ireland after decades of conflict known as the Troubles."),
        new TimelineEvent("59", [2005], "London bombings (7/7)", "A series of coordinated terrorist attacks targeted London's public transport system, resulting in significant loss of life."),
        new TimelineEvent("60", [2012], "London hosts the Olympic Games", "London hosted the Olympic Games for the third time, showcasing the UK on the world stage."),
        new TimelineEvent("61", [2016], "EU Referendum (Brexit)", "A national referendum resulted in a majority vote for the UK to leave the European Union."),
        new TimelineEvent("62", [2020], "COVID-19 pandemic in the UK", "The COVID-19 pandemic had a major impact on the UK, leading to lockdowns and significant changes in daily life."),
    ]
}