import { TimelinePeriod} from "../Entities/TimelinePeriod";
import {TimelineEvent} from "../Entities/TimelineEvent";
export const seedEvents: TimelineEvent[] = [
    new TimelineEvent([-800000], "First humans arrive in Britain", "Archaeological evidence suggests that the earliest humans arrived in what is now Britain around 800,000 years ago, during the Paleolithic era."),
    new TimelineEvent([-4000], "Neolithic farmers settle in Britain", "Around 4000 BCE, people began to settle, farm, and build monuments such as Stonehenge, marking the start of the Neolithic period in Britain."),
    new TimelineEvent([-2500], "Construction of Stonehenge begins", "Stonehenge, one of the most famous prehistoric monuments in the world, was constructed in several stages starting around 2500 BCE."),
    new TimelineEvent([-800], "Iron Age and Celtic culture in Britain", "The Iron Age saw the arrival of the Celts, who brought new technologies and established tribal kingdoms across Britain."),
    new TimelineEvent([43], "Roman conquest of Britain", "The Romans, led by Emperor Claudius, invaded and began the conquest of Britain in 43 CE, establishing the province of Britannia."),
    new TimelineEvent([122], "Construction of Hadrian's Wall", "Hadrian's Wall was built by the Romans to protect the northern border of their province from tribes in what is now Scotland."),
    new TimelineEvent([410], "End of Roman rule in Britain", "Roman administration and legions withdrew from Britain, leaving the local population to govern themselves."),
    new TimelineEvent([450], "Anglo-Saxon settlement begins", "After the Romans left, groups such as the Angles, Saxons, and Jutes migrated to Britain, forming several kingdoms."),
    new TimelineEvent([597], "Arrival of St Augustine", "St Augustine arrived in Kent to convert the Anglo-Saxons to Christianity, becoming the first Archbishop of Canterbury."),
    new TimelineEvent([793], "Viking raid on Lindisfarne", "The first major Viking raid in Britain occurred at the monastery of Lindisfarne, marking the start of the Viking Age."),
    new TimelineEvent([871], "Alfred the Great becomes King of Wessex", "Alfred the Great defended his kingdom against Viking invasions and promoted learning and legal reform."),
    new TimelineEvent([927], "Athelstan becomes first King of England", "Athelstan united the various Anglo-Saxon kingdoms, becoming the first King of a unified England."),
    new TimelineEvent([1066], "Battle of Hastings and Norman Conquest", "William the Conqueror defeated King Harold II at the Battle of Hastings, beginning Norman rule in England."),
    new TimelineEvent([1086], "Domesday Book completed", "The Domesday Book was a great survey commissioned by William the Conqueror to assess land and resources in England."),
    new TimelineEvent([1170], "Murder of Thomas Becket", "Archbishop Thomas Becket was murdered in Canterbury Cathedral, becoming a martyr and symbol of church-state conflict."),
    new TimelineEvent([1215], "Magna Carta signed", "King John agreed to the Magna Carta, a charter limiting royal power and establishing certain legal rights."),
    new TimelineEvent([1284], "Statute of Rhuddlan", "The Statute of Rhuddlan annexed Wales to the English crown, establishing English rule over Wales."),
    new TimelineEvent([1314], "Battle of Bannockburn", "Scottish forces led by Robert the Bruce defeated the English, securing Scottish independence for a time."),
    new TimelineEvent([1348], "Black Death arrives in Britain", "The Black Death, a devastating plague, killed a large proportion of the British population in the mid-14th century."),
    new TimelineEvent([1381], "Peasants' Revolt", "A major uprising of peasants and workers in England, protesting taxes and social inequality."),
    new TimelineEvent([1415], "Battle of Agincourt", "King Henry V led the English to a famous victory against the French during the Hundred Years' War."),
    new TimelineEvent([1485], "Battle of Bosworth Field", "The last major battle of the Wars of the Roses, resulting in the death of Richard III and the start of the Tudor dynasty."),
    new TimelineEvent([1534], "Act of Supremacy", "King Henry VIII declared himself Supreme Head of the Church of England, breaking from the Roman Catholic Church."),
    new TimelineEvent([1588], "Defeat of the Spanish Armada", "The English navy defeated the Spanish Armada, establishing England as a major naval power."),
    new TimelineEvent([1603], "Union of the Crowns", "James VI of Scotland became James I of England, uniting the crowns of England and Scotland."),
    new TimelineEvent([1605], "Gunpowder Plot", "A failed attempt by Guy Fawkes and others to blow up the Houses of Parliament and assassinate King James I."),
    new TimelineEvent([1642], "English Civil War begins", "Conflict broke out between supporters of King Charles I and Parliament, leading to a series of civil wars."),
    new TimelineEvent([1649], "Execution of Charles I", "King Charles I was executed after being tried for treason, and England briefly became a republic."),
    new TimelineEvent([1660], "Restoration of the monarchy", "The monarchy was restored under Charles II after the collapse of the republican government."),
    new TimelineEvent([1665], "Great Plague of London", "The last major outbreak of bubonic plague in England, killing thousands in London."),
    new TimelineEvent([1666], "Great Fire of London", "A devastating fire destroyed much of the City of London, leading to major rebuilding efforts."),
    new TimelineEvent([1688], "Glorious Revolution", "William of Orange and Mary II took the throne, establishing constitutional monarchy and parliamentary supremacy."),
    new TimelineEvent([1707], "Act of Union between England and Scotland", "The Act of Union created the Kingdom of Great Britain, uniting England and Scotland under one parliament."),
    new TimelineEvent([1756], "Start of the Seven Years' War", "A global conflict involving Britain, which expanded its empire and influence overseas."),
    new TimelineEvent([1776], "American Declaration of Independence", "The American colonies declared independence from Britain, leading to the American Revolutionary War."),
    new TimelineEvent([1801], "Act of Union with Ireland", "The Act of Union joined Great Britain and Ireland, creating the United Kingdom of Great Britain and Ireland."),
    new TimelineEvent([1805], "Battle of Trafalgar", "Admiral Lord Nelson led the British navy to victory over the French and Spanish fleets, securing British naval dominance."),
    new TimelineEvent([1815], "Battle of Waterloo", "The Duke of Wellington defeated Napoleon at Waterloo, ending the Napoleonic Wars."),
    new TimelineEvent([1832], "Great Reform Act", "The Great Reform Act reformed the British electoral system, expanding the right to vote and redistributing parliamentary seats."),
    new TimelineEvent([1833], "Abolition of slavery in the British Empire", "The Slavery Abolition Act 1833 ended slavery throughout most of the British Empire."),
    new TimelineEvent([1837], "Queen Victoria ascends the throne", "Queen Victoria began her long reign, marking the start of the Victorian era."),
    new TimelineEvent([1851], "The Great Exhibition", "The Great Exhibition in London showcased British industry and innovation to the world."),
    new TimelineEvent([1914], "Start of World War I", "Britain entered World War I, a global conflict that had a profound impact on British society and the world."),
    new TimelineEvent([1918], "Representation of the People Act", "The Representation of the People Act 1918 gave the vote to all men over 21 and women over 30 in Britain."),
    new TimelineEvent([1928], "Equal franchise for women", "The Representation of the People Act 1928 gave women the same voting rights as men in Britain."),
    new TimelineEvent([1939], "Start of World War II", "Britain declared war on Germany, beginning its involvement in World War II."),
    new TimelineEvent([1940], "Battle of Britain", "The Royal Air Force defended the UK against large-scale attacks by Nazi Germany's air force."),
    new TimelineEvent([1942], "Beveridge Report published", "The Beveridge Report laid the foundations for the modern welfare state in Britain."),
    new TimelineEvent([1945], "End of World War II in Europe", "Victory in Europe Day (VE Day) marked the end of World War II in Europe."),
    new TimelineEvent([1948], "Establishment of the NHS", "The National Health Service (NHS) was founded, providing free healthcare to all UK residents."),
    new TimelineEvent([1952], "Queen Elizabeth II becomes monarch", "Queen Elizabeth II ascended the throne following the death of her father, King George VI."),
    new TimelineEvent([1956], "Suez Crisis", "A diplomatic and military crisis involving Britain, France, Egypt, and Israel over control of the Suez Canal."),
    new TimelineEvent([1969], "First man on the moon", "Neil Armstrong became the first person to walk on the moon, watched by millions in the UK and worldwide."),
    new TimelineEvent([1973], "UK joins the European Economic Community", "Britain joined the EEC, a precursor to the European Union, marking a major shift in economic policy."),
    new TimelineEvent([1979], "Margaret Thatcher becomes Prime Minister", "Margaret Thatcher became the UK's first female Prime Minister, leading major economic and social reforms."),
    new TimelineEvent([1982], "Falklands War", "Britain fought and won a conflict with Argentina over the Falkland Islands in the South Atlantic."),
    new TimelineEvent([1997], "Devolution in Scotland and Wales", "Referendums led to the creation of the Scottish Parliament and Welsh Assembly, devolving powers from Westminster."),
    new TimelineEvent([1998], "Good Friday Agreement", "The Good Friday Agreement brought peace to Northern Ireland after decades of conflict known as the Troubles."),
    new TimelineEvent([2005], "London bombings (7/7)", "A series of coordinated terrorist attacks targeted London's public transport system, resulting in significant loss of life."),
    new TimelineEvent([2012], "London hosts the Olympic Games", "London hosted the Olympic Games for the third time, showcasing the UK on the world stage."),
    new TimelineEvent([2016], "EU Referendum (Brexit)", "A national referendum resulted in a majority vote for the UK to leave the European Union."),
    new TimelineEvent([2020], "COVID-19 pandemic in the UK", "The COVID-19 pandemic had a major impact on the UK, leading to lockdowns and significant changes in daily life."),
    // ...additional events can be added to reach up to 100 if needed, focusing on key monarchs, reforms, wars, and cultural milestones...
];

export const seedEvents2: TimelineEvent[] = [
    new TimelineEvent([-3200], "Unification of Egypt"),
    new TimelineEvent([-3100], "First Cuneiform Writing"),
    new TimelineEvent([-2700], "Step Pyramid of Djoser"),
    new TimelineEvent([-2560], "Great Pyramid of Giza"),
    new TimelineEvent([-2334], "Founding of Akkadian Empire"),
    new TimelineEvent([-2270], "Construction of the Great Ziggurat of Ur"),
    // new TimelineEvent([-2150], "Old Kingdom of Egypt collapse"), not important 
    new TimelineEvent([-2100], "Epic of Gilgamesh"),
    new TimelineEvent([-2000], "Minoan civilization peak"),
    new TimelineEvent([-1894], "Babylonian Empire establishment"),
    new TimelineEvent([-1754], "Code of Hammurabi"), //verify date
    new TimelineEvent([-1600], "Shang Dynasty commences"),
    new TimelineEvent([-1500], "Hittite Empire peak"),
    new TimelineEvent([-1350], "Mycenaean Greece peak"),
    
    // new TimelineEvent([-1500], "Vedic period beginning"), turn into period
    // new TimelineEvent([-1479], "Hatshepsut's reign"),
    // new TimelineEvent([-1353], "Akhenaten's monotheism"),
    new TimelineEvent([-1323], "Tutankhamun's death"),
    new TimelineEvent([-1274], "Battle of Kadesh"),
    new TimelineEvent([-1213], "Ramesses II death"),
    new TimelineEvent([-1200], "Bronze Age collapse"),
    new TimelineEvent([-1184], "Fall of Troy", "Date is debated, but often placed around 12th century BCE based on archaeological evidence and ancient texts. The traditional date of 1184 BCE comes from the ancient Greek historian Eratosthenes, who calculated it based on the reigns of various kings and events in Greek mythology. However, modern archaeological findings suggest that the actual fall of Troy may have occurred around 1250-1190 BCE. The exact date remains uncertain due to the legendary nature of the event and the lack of definitive historical records."),
    new TimelineEvent([-1122], "Zhou conquest of Shang"),
    new TimelineEvent([-1000], "David conquers Jerusalem"),
    new TimelineEvent([-970], "Solomon's Temple"),
    new TimelineEvent([-814], "Founding of Carthage"),
    new TimelineEvent([-776], "First Olympic Games"),
    new TimelineEvent([-753], "Founding of Rome"),
    new TimelineEvent([-671], "Assyrian conquest of Egypt"),
    new TimelineEvent([-689], "Siege of Babylon by Assyria"),
    new TimelineEvent([-660], "Founding of Japan"),
    // new TimelineEvent([-626], "Neo-Babylonian Empire"),
    new TimelineEvent([-612], "Fall of Nineveh"),
    new TimelineEvent([-586], "Jerusalem destruction by the Babylonians"),
    new TimelineEvent([-563], "Buddha's birth"),
    new TimelineEvent([-551], "Confucius' birth"),
    new TimelineEvent([-550], "Persian Empire foundation by Cyrus the Great"),
    new TimelineEvent([-538], "Cyrus Cylinder - First Charter of Human Rights"),
    new TimelineEvent([-509], "Founding of the Roman Republic"),
    new TimelineEvent([-508], "Athenian democracy establishment"),
    new TimelineEvent([-490], "Battle of Marathon"),
    new TimelineEvent([-480], "Battle of Thermopylae"),
    new TimelineEvent([-480], "Battle of Salamis"),
    new TimelineEvent([-479], "Battle of Plataea"),
    new TimelineEvent([-431], "Peloponnesian War begins"),//period for wars
    
    new TimelineEvent([-399], "Socrates' execution"),//?
    new TimelineEvent([-387], "Plato's Academy founded"),//?
    
    new TimelineEvent([-336], "Philip II assassination"),
    new TimelineEvent([-334], "Alexander's Persian invasion"),
    new TimelineEvent([-323], "Alexander's death"),
    new TimelineEvent([-264], "First Punic War begins"), // insert battles here
    new TimelineEvent([-221], "Chinese unification by Qin"),
    new TimelineEvent([-49], "Caesar becomes dictator"),
    new TimelineEvent([-44], "Caesar's assassination"),
    
   
    new TimelineEvent([476], "Fall of Western Roman Empire"),
    new TimelineEvent([622], "Hijra - Beginning of Islamic Calendar"),
    new TimelineEvent([800], "Charlemagne Crowned Emperor"),
    new TimelineEvent([1066], "Norman Conquest of England"),
    new TimelineEvent([1347], "Black Death Begins"),
    new TimelineEvent([1453], "Fall of Constantinople"),
    new TimelineEvent([1492], "Columbus Reaches the Americas"),
    new TimelineEvent([1517], "Protestant Reformation Begins"),
    new TimelineEvent([1776], "American Declaration of Independence"),
    new TimelineEvent([1789], "French Revolution Begins"),
    new TimelineEvent([1969], "Moon Landing"),
    new TimelineEvent([2000], "Kostas Birthday"),
    new TimelineEvent([2003], "Anastasia Birthday")
    
];

export const seedPeriods = [
    // Prehistoric Periods
    // new TimelinePeriod([-3300000], [-12000], "Paleolithic Era"),
    // new TimelinePeriod([-12000], [-8000], "Mesolithic Era"),
    // new TimelinePeriod([-8000], [-3000], "Neolithic Era"),
    new TimelinePeriod([-3300], [-1200], "Bronze Age"),
    new TimelinePeriod([-1200], [550], "Iron Age"),
    new TimelinePeriod([800], [1000], "Classical Antiquity"),
    new TimelinePeriod([500], [1453], "Middle Ages"),
    new TimelinePeriod([1400], [1600], "Renaissance"),
    new TimelinePeriod([1418], [1620], "Age of Discovery", 1),
    // new TimelinePeriod([1600], [1850], "Age of Sail", 1),
    // new TimelinePeriod([1600], [1750], "Baroque Period"),
    new TimelinePeriod([1517], [1648], "Protestant Reformation"),
    new TimelinePeriod([1760], [1840], "First Industrial Revolution"),
    new TimelinePeriod([1815], [1914], "Pax Britannica"),
    new TimelinePeriod([1840], [1914], "Second Industrial Revolution"),
    new TimelinePeriod([1880], [1914], "Belle Époque"),
    new TimelinePeriod([1914], [1918], "World War I"),
    new TimelinePeriod([1929], [1939], "Great Depression"),
    new TimelinePeriod([1939], [1945], "World War II"),
    new TimelinePeriod([1945], [1991], "Cold War Era"),
    new TimelinePeriod([1991], [2024], "Post-Cold War Era"),
];