using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using everything_timeline;
using Microsoft.Extensions.Configuration;
using DbContext = everything_timeline.DbContext;
using Runners;

// Auto-generated by VS Code C# Dev Tools - Runner feature
// DI setup extracted from source Program.cs
// Source timestamp: 2026-05-19T00:30:23.279Z

// Set environment variables for appsettings.{Environment}.json loading
System.Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", RunnerSetup.Environment);
System.Environment.SetEnvironmentVariable("DOTNET_ENVIRONMENT", RunnerSetup.Environment);

var builder = FunctionsApplication.CreateBuilder(args);

var clientId = Environment.GetEnvironmentVariable("AzureAd__ClientId");
var authority = Environment.GetEnvironmentVariable("AzureAd__Authority");
var issuer = Environment.GetEnvironmentVariable("AzureAd__Issuer");

builder.ConfigureFunctionsWebApplication();

builder.UseMiddleware<AuthMiddleware>();

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = authority;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuers = [issuer],
            ValidateAudience = true,
            ValidAudiences = [clientId],
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true
        };
    });

builder.Services.AddAuthorization();

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

builder.Services.AddDbContext<DbContext>(options =>
{
    var connectionString = Environment.GetEnvironmentVariable("SqlConnectionString") ?? builder.Configuration.GetConnectionString("SqlConnectionString");
    options.UseSqlServer(connectionString, sqlOptions => { sqlOptions.EnableRetryOnFailure(); });
});

// Services
builder.Services.AddScoped<IRepository, Repository>();
builder.Services.AddApplicationInsightsTelemetryWorkerService().ConfigureFunctionsApplicationInsights();

// Apply custom runner DI configuration
RunnerSetup.ConfigureServices(builder.Services);

// Forward interface registrations to their concrete implementation types
if (RunnerSetup.AutoRegisterConcreteTypes) RegisterConcreteImplementationsAsSelf(builder.Services);

var serviceProvider = builder.Services.BuildServiceProvider();

static void RegisterConcreteImplementationsAsSelf(IServiceCollection services)
{
    var snapshot = services.ToList();
    var registered = new System.Collections.Generic.HashSet<Type>(
        snapshot
            .Where(d => d.ServiceType is { IsClass: true, IsAbstract: false } && !d.ServiceType.IsGenericTypeDefinition)
            .Select(d => d.ServiceType));

    // Phase 1: Direct registrations (ImplementationType / ImplementationInstance known)
    foreach (var d in snapshot)
    {
        if (d.ServiceType is null || d.ServiceType.IsGenericTypeDefinition) continue;
        if (!d.ServiceType.IsInterface && !d.ServiceType.IsAbstract) continue;
        var impl = d.ImplementationType ?? d.ImplementationInstance?.GetType();
        if (impl is null || impl.IsAbstract || impl.IsInterface || impl.IsGenericTypeDefinition) continue;
        if (impl == d.ServiceType || !registered.Add(impl)) continue;
        services.Add(new ServiceDescriptor(impl, sp => sp.GetRequiredService(d.ServiceType)!, d.Lifetime));
    }

    // Phase 2: Factory registrations — resolve via a temp provider to discover runtime types
    var factories = snapshot.Where(d =>
        d.ServiceType is not null && !d.ServiceType.IsGenericTypeDefinition &&
        (d.ServiceType.IsInterface || d.ServiceType.IsAbstract) &&
        d.ImplementationType is null && d.ImplementationInstance is null).ToList();
    if (factories.Count > 0)
    {
        using var tempSp = services.BuildServiceProvider();
        using var scope = tempSp.CreateScope();
        foreach (var d in factories)
        {
            try
            {
                var instance = scope.ServiceProvider.GetService(d.ServiceType!);
                if (instance is null) continue;
                var implType = instance.GetType();
                if (implType.IsAbstract || implType == d.ServiceType || !registered.Add(implType)) continue;
                services.Add(new ServiceDescriptor(implType, sp => sp.GetRequiredService(d.ServiceType!)!, d.Lifetime));
            }
            catch { /* Service not resolvable yet — skip */ }
        }
    }
}

// --- Runner Execution (auto-generated) ---
